name: highview
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^2.0.0
  cloud_firestore: ^2.3.0
  cloud_functions: ^2.0.0
  firebase_core: ^1.3.0
  flutter_form_builder: ^6.0.1
  get: ^4.1.4
  velocity_x: ^3.3.0
  google_sign_in: ^5.0.4
  provider:
  font_awesome_flutter: ^9.1.0
  cached_network_image: ^3.0.0
  flutter_spinkit: ^5.0.0
  firebase_storage: ^9.0.0
  splashscreen: ^1.3.5
  flutter_dialogflow_v2: ^0.3.2
#  flutter_dialogflow: ^0.1.3
  bubble: ^1.1.9+1
  dialogflow_grpc: ^0.2.9
  cupertino_icons: ^1.0.2
  sound_stream: ^0.3.0
  rxdart:
  stretchy_header: ^2.0.0
  flutter_staggered_grid_view: ^0.4.0
  flutter_staggered_animations: ^1.0.0
  flutter_datetime_picker: ^1.5.1
  timeago: ^2.0.29
  flutter_chat_bubble: ^1.0.2
  path_drawing: ^0.5.1

dependency_overrides:
  http:
  firebase_storage_web:
  googleapis_auth: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
   - family: Montserrat
     fonts:
       - asset: fonts/Montserrat-Regular.ttf

